language: python
python:
  - 2.6
  - 2.7

before_install:
    - sudo apt-get install python-dev libevent-dev

install:
  - "python setup.py install"

script: nosetests

after_success:
  - pip install coveralls
  - coverage run --source=gqueue setup.py -q nosetests
  - coveralls

notifications:
  email: false
